### ISSUE TITLE
Plugin installer requires ES to be running

### ISSUE THREAD

**Issue by michaelklishin** [vkhatri/chef-elasticsearch-cluster#16]
Plugin installation will fail when the service isn't running because the provider tries to query node info for the list of plugins. I don't know if this really can be avoided but it can lead to pretty obscure issues and is quite confusing.

**Comment by michaelklishin** [comment]
This is quite ironic: the AWS plugin cannot be installed without ES running but ES won't start because discovery type requires the AWS plugin to be installed.

**Comment by michaelklishin** [comment]
This is a deal breaker for AWS plugin users (otherwise this cookbook is significantly better than the official one).

I can think of two solutions:
- Do not check existing plugins at all
- Handle exceptions and consider the list of plugins to be empty

WDYT? FWIW, the official cookbook does not check existing plugins. I see no major harm in that — am I missing something? Will the ES's `plugin` tool take care of plugin upgrades?

**Comment by vkhatri** [comment]
@michaelklishin i can think of below solution
1. `delay` the service start so that plugins (such as AWS) required for cluster/configuration can be installed before chef `starts` the elasticsearch `service`
2. add `ignore_error` attribute to resource `plugin` to execute plugin install even if elasticsearch service is `down` 
3. add `notify_restart` attribute to resource `plugin` to trigger elasticsearch service `reload`

i think that should cover it. i will work on it shortly.

**Comment by michaelklishin** [comment]
Yup, notifications is probably the right thing to do but ignoring errors from `Net::HTTP` may still be necessary. Thank you, hopefully with this issue resolved I will be able to provision ES on AWS entirely with this cookbook :+1:

**Comment by vkhatri** [comment]
@michaelklishin this should take care of it

**Comment by michaelklishin** [comment]
Thank you, I will give it a try this evening!
